## MLP for Binary Classification

In this lab, you will use the Ionosphere data binary (two-class) classification dataset to demonstrate an MLP for binary classification.

This dataset involves predicting whether a structure is in the atmosphere or not given radar returns.

The dataset will be downloaded automatically using Pandas, but you can learn more in the links below.

[Ionosphere Dataset (csv)](https://raw.githubusercontent.com/jbrownlee/Datasets/master/ionosphere.csv)

[Ionosphere Dataset Description (csv)](https://raw.githubusercontent.com/jbrownlee/Datasets/master/ionosphere.names)


Your task for this is lab is to develop a Keras-based Multi-Layer Perceptron model for this data set. Remember the number of output layers is equal to the number of classes.

Following we have provided some piece of code to you while you need to complete the rest of the code on your own.



In [82]:
# Importing Libraries
import numpy as np

# Your code to import read_csv class from pandas
import pandas as pd
from pandas import read_csv

# Your code to import train_test_split class from sklearn. Follow link https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.train_test_split.html
from sklearn.model_selection import train_test_split

from sklearn.preprocessing import LabelEncoder
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense

# Read the dataset from the path below. Store the data in a pandas dataframe named 'df'

Link to API - https://pandas.pydata.org/docs/reference/api/pandas.read_csv.html

In [83]:
path = 'https://raw.githubusercontent.com/jbrownlee/Datasets/master/ionosphere.csv'
# Your code to read the csv from the above path.
df = pd.read_csv(path, header = None)

See the sample dataset. Print few rows of the dataset. Use dataframe.head() method.

Link to API:  https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.head.html

In [84]:
# Your code to print first few rows of the dataset.
df.head()

0   1        2        3        4        5        6        7        8   \
0   1   0  0.99539 -0.05889  0.85243  0.02306  0.83398 -0.37708  1.00000   
1   1   0  1.00000 -0.18829  0.93035 -0.36156 -0.10868 -0.93597  1.00000   
2   1   0  1.00000 -0.03365  1.00000  0.00485  1.00000 -0.12062  0.88965   
3   1   0  1.00000 -0.45161  1.00000  1.00000  0.71216 -1.00000  0.00000   
4   1   0  1.00000 -0.02401  0.94140  0.06531  0.92106 -0.23255  0.77152   

        9   ...       25       26       27       28       29       30  \
0  0.03760  ... -0.51171  0.41078 -0.46168  0.21266 -0.34090  0.42267   
1 -0.04549  ... -0.26569 -0.20468 -0.18401 -0.19040 -0.11593 -0.16626   
2  0.01198  ... -0.40220  0.58984 -0.22145  0.43100 -0.17365  0.60436   
3  0.00000  ...  0.90695  0.51613  1.00000  1.00000 -0.20099  0.25682   
4 -0.16399  ... -0.65158  0.13290 -0.53206  0.02431 -0.62197 -0.05707   

        31       32       33  34  
0 -0.54487  0.18641 -0.45300   g  
1 -0.06288 -0.13738 -0.02447   b  
2 -0.24180  0.56045 -0.38238   g  
3  1.00000 -0.32382  1.00000   b  
4 -0.59573 -0.04608 -0.65697   g  

[5 rows x 35 columns]

Print the basic info of the dataset. Use dataframe.info() from pandas library


In [85]:
# Your code to print information about the dataframe
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 351 entries, 0 to 350
Data columns (total 35 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   0       351 non-null    int64  
 1   1       351 non-null    int64  
 2   2       351 non-null    float64
 3   3       351 non-null    float64
 4   4       351 non-null    float64
 5   5       351 non-null    float64
 6   6       351 non-null    float64
 7   7       351 non-null    float64
 8   8       351 non-null    float64
 9   9       351 non-null    float64
 10  10      351 non-null    float64
 11  11      351 non-null    float64
 12  12      351 non-null    float64
 13  13      351 non-null    float64
 14  14      351 non-null    float64
 15  15      351 non-null    float64
 16  16      351 non-null    float64
 17  17      351 non-null    float64
 18  18      351 non-null    float64
 19  19      351 non-null    float64
 20  20      351 non-null    float64
 21  21      351 non-null    float64
 22  22

Print the shape of the dataframe. Select suitable API call from the pandas library

In [86]:
# Your code to print the shape of the dataset
df.shape

(351, 35)

# Separate the input and output from the dataframe. Input is all columns besides last column. Output is the last column.


In [97]:
X = df.values[:, :-1]
# Your code to get y - Hint y = df.values[:, some parameters]
y = df.values[:, -1]

We have converted everthing in X to 'float' and the letters in column y to the numbers in the following cell.

In [98]:
X = X.astype('float32')
y = LabelEncoder().fit_transform(y)

Printing the genral information of the X and y in the following cell

In [99]:
# Your code to print X
print(X)

# Your code to print y
print(y)

# your code to print shape of X. Remember X is a numpy array
print(X.shape)

# your code to print shape of y. Remember y is a numpy array
print(y.shape)

[[ 1.       0.       0.99539 ... -0.54487  0.18641 -0.453  ]
 [ 1.       0.       1.      ... -0.06288 -0.13738 -0.02447]
 [ 1.       0.       1.      ... -0.2418   0.56045 -0.38238]
 ...
 [ 1.       0.       0.94701 ...  0.00442  0.92697 -0.00577]
 [ 1.       0.       0.90608 ... -0.03757  0.87403 -0.16243]
 [ 1.       0.       0.8471  ... -0.06678  0.85764 -0.06151]]
[1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0
 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 1 0 1 0 1 0 1 0 1 0 1 0 1 0
 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0
 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1

* Separate X and y into training and test set with a ratio of your choice.
* Print the shapes of the resulting arrays.
* Get the number of features from X_train. Remember the number of features are the number of inputs.

Use sklearn train_test_split class.
https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.train_test_split.html


In [100]:
# Your code to separate the data into trauning and test set.
X_train, X_test, y_train, y_test = train_test_split(X, y)

# Your code to print shape of X_train
# Your code to print shape of X_test
# Your code to print shape of y_train
# Your code to print shape of X_test
print(X_train)
print(X_test)
print(y_train)
print(y_test)

n_features = X_train.shape[1]

[[ 1.       0.      -1.      ... -1.       0.       0.     ]
 [ 1.       0.       0.93537 ...  0.64363 -0.47419  0.55835]
 [ 1.       0.       1.      ...  1.       1.       1.     ]
 ...
 [ 1.       0.       1.      ... -0.04142  0.02249 -0.02017]
 [ 1.       0.       0.41932 ... -0.07464 -0.00526 -0.06314]
 [ 1.       0.       0.90547 ...  0.098    0.75495  0.46301]]
[[ 1.       0.       0.88208 ... -0.57377  0.42189 -0.58086]
 [ 1.       0.       0.99539 ... -0.54487  0.18641 -0.453  ]
 [ 1.       0.       0.97513 ...  0.06217  0.98934  0.09947]
 ...
 [ 1.       0.       0.64947 ... -0.1895   0.01336 -0.27201]
 [ 0.       0.      -1.      ...  0.      -1.       1.     ]
 [ 1.       0.       1.      ...  0.10067  1.       0.10067]]
[0 1 0 0 1 1 0 1 1 1 1 1 1 1 1 1 1 1 0 1 1 0 1 1 0 1 1 1 0 1 1 1 0 1 0 1 0
 1 1 1 1 1 1 0 0 1 0 0 0 1 1 1 0 0 1 1 1 1 0 1 0 1 0 1 1 0 0 1 0 0 1 1 1 1
 1 1 0 1 1 1 1 1 1 0 0 0 0 1 1 0 1 1 0 1 1 1 1 1 1 0 0 1 1 0 0 0 1 1 0 0 0
 1 1 1 0 1 0 1 1 1 1 1 1 1 1 1 

# Creating a Multi-layer Perceptron using Keras.
We have added first and last layers. Create the hidden layers of your choise.
You can chose any number of hidden layers and activation function of your chose
https://keras.io/api/layers/core_layers/dense/

In [121]:
model = Sequential()
model.add(Dense(10, activation='relu', input_shape=(n_features,)))
#
# Add as many layers with activation functions of your choice
#
model.add(Dense(4, activation = 'relu'))
model.add(Dense(5, activation = 'softmax'))

model.add(Dense(1, activation='sigmoid'))

In the next cell, we trained the above neural network model and tested its accuracy. As this concept has still not benn covered in the class, just run the code to check the accuracy.

In [122]:
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
model.fit(X_train, y_train, epochs=150, batch_size=32, verbose=0)

loss, acc = model.evaluate(X_test, y_test, verbose=0)
print('Test Accuracy: %.3f' % acc)

Test Accuracy: 0.909


** How much accuracy have you got? Compare the accuracy with your peers. **
** Now, change your model and activation function to get the better accuracy as compared to your peers **

## **Important:** Document in your lab logbook the accuracy of the improved model. Do not include any code or explanations in your lab logbook. Simply record the accuracy. For example, if the obtained accuracy is 0.98, then enter "0.98" in your lab logbook.

## In addition to the accuracy, also document the output of the neural network as provided in Task 2.



Next, we have provided the code to predict on an unknown value.
We will cover these concepts later in the class. For now, just run the code to see the prediction.

In [123]:
row = [1,0,0.99539,-0.05889,0.85243,0.02306,
       0.83398,-0.37708,1,0.03760,0.85243,-0.17755,
       0.59755,-0.44945,0.60536,-0.38223,0.84356,
       -0.38542,0.58212,-0.32192,0.56971,-0.29674,0.36946,
       -0.47357,0.56811,-0.51171,0.41078,-0.46168,0.21266,
       -0.34090,0.42267,-0.54487,0.18641,-0.45300]
yhat = model.predict([row])
print('Predicted: %.3f' % yhat)

1/1 [==============================] - 0s 47ms/step
Predicted: 0.887


### Try out the same model with Keras Functional models!
Refer to [Keras](https://keras.io/) for more details and tutorials for the same.

In [141]:
model = Sequential()
model.add(Dense(10, activation='relu', input_shape=(n_features,)))
#
# Add as many layers with activation functions of your choice
#
model.add(Dense(4, activation = 'relu'))
model.add(Dense(5, activation = 'softmax'))
model.add(Dense(64, activation = 'tanh'))
model.add(Dense(10, activation = 'softplus'))
model.add(Dense(5, activation = 'softsign'))
model.add(Dense(34, activation = 'selu'))
model.add(Dense(1, activation = 'elu'))
model.add(Dense(69, activation = 'exponential'))
model.add(Dense(11, activation = 'leaky_relu'))


model.add(Dense(1, activation='sigmoid'))

In [142]:
print(model.summary())

Model: "sequential_18"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_88 (Dense)            (None, 10)                350       
                                                                 
 dense_89 (Dense)            (None, 4)                 44        
                                                                 
 dense_90 (Dense)            (None, 5)                 25        
                                                                 
 dense_91 (Dense)            (None, 64)                384       
                                                                 
 dense_92 (Dense)            (None, 10)                650       
                                                                 
 dense_93 (Dense)            (None, 5)                 55        
                                                                 
 dense_94 (Dense)            (None, 34)              

In the next cell, we trained the above neural network model and tested its accuracy. As this concept has still not benn covered in the class, just run the code to check the accuracy.

In [143]:
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
model.fit(X_train, y_train, epochs=150, batch_size=32, verbose=2)

loss, acc = model.evaluate(X_test, y_test, verbose=2)
print('Test Accuracy: %.3f' % acc)

Epoch 1/150
9/9 - 0s - loss: 1.1412 - accuracy: 0.3498 - 279ms/epoch - 31ms/step
Epoch 2/150
9/9 - 0s - loss: 0.6694 - accuracy: 0.6198 - 5ms/epoch - 550us/step
Epoch 3/150
9/9 - 0s - loss: 0.6858 - accuracy: 0.6502 - 5ms/epoch - 509us/step
Epoch 4/150
9/9 - 0s - loss: 0.6578 - accuracy: 0.6502 - 5ms/epoch - 517us/step
Epoch 5/150
9/9 - 0s - loss: 0.6449 - accuracy: 0.6502 - 5ms/epoch - 565us/step
Epoch 6/150
9/9 - 0s - loss: 0.6503 - accuracy: 0.6502 - 5ms/epoch - 568us/step
Epoch 7/150
9/9 - 0s - loss: 0.6510 - accuracy: 0.6502 - 5ms/epoch - 565us/step
Epoch 8/150
9/9 - 0s - loss: 0.6459 - accuracy: 0.6502 - 5ms/epoch - 605us/step
Epoch 9/150
9/9 - 0s - loss: 0.6462 - accuracy: 0.6502 - 5ms/epoch - 528us/step
Epoch 10/150
9/9 - 0s - loss: 0.6412 - accuracy: 0.6502 - 6ms/epoch - 642us/step
Epoch 11/150
9/9 - 0s - loss: 0.6295 - accuracy: 0.6502 - 5ms/epoch - 593us/step
Epoch 12/150
9/9 - 0s - loss: 0.6095 - accuracy: 0.6502 - 5ms/epoch - 564us/step
Epoch 13/150
9/9 - 0s - loss: 0.5619

In [144]:
row = [1,0,0.99539,-0.05889,0.85243,0.02306,
       0.83398,-0.37708,1,0.03760,0.85243,-0.17755,
       0.59755,-0.44945,0.60536,-0.38223,0.84356,
       -0.38542,0.58212,-0.32192,0.56971,-0.29674,0.36946,
       -0.47357,0.56811,-0.51171,0.41078,-0.46168,0.21266,
       -0.34090,0.42267,-0.54487,0.18641,-0.45300]
yhat = model.predict([row])
print('Predicted: %.3f' % yhat)

1/1 [==============================] - 0s 56ms/step
Predicted: 1.000
